### ISSUE TITLE
Where are const FLAGs?

### ISSUE THREAD

**Issue by finscn** [mapeditor/tiled-extensions#14]
I need there const FLAGs: 
```
const FLIPPED_HORIZONTALLY_FLAG = 0x80000000;
const FLIPPED_VERTICALLY_FLAG = 0x40000000;
const FLIPPED_DIAGONALLY_FLAG = 0x20000000;

```

But I can't find them in the doc https://www.mapeditor.org/docs/scripting/ 

Could you help me ? thanks.

**Comment by bjorn** [comment]
> I see Tile.FlippedHorizontally === 1 , but in tile Layer , the gid's FlippedHorizontally flag is 0x80000000
> 
> Is there a const save the 0x80000000 ?

The `edit.setTile(x,y,tile, flags)` API needs the flag as it is in `Tile.FlippedHorizontally`. The value `0x80000000` is only used in the TMX / JSON formats, but has no relevance to the JS API.

**Comment by bjorn** [comment]
> I should look into adding a link in the docs for `TileLayerEdit.setTile`.

Added as of https://github.com/mapeditor/tiled/commit/38189fb681c83ffe7e558fb5d82ce9eb1a4a53ba.
